### ISSUE TITLE
Background issues

### ISSUE THREAD

**Issue by ashfurrow** [BlackrockDigital/startbootstrap-clean-blog#10]
Hey there! Love this blog theme! I use it at http://ashfurrow.com/ and I've enjoyed learning from your code. 

One thing is that `intro-header`'s background colour isn't respected, at least on Safari. It's always white. I think that I've narrowed the problem down to [these few lines](https://github.com/IronSummitMedia/startbootstrap-clean-blog/blob/53316cb62ee70afd6297bdca53be89044f00d479/less/clean-blog.less#L159-L160):

```less
.intro-header {
	background-color: @gray; 
	background: no-repeat center center; 
```

The first line sets the background colour, but it's overriden by the following `background:` specifier. I switched the order of the two lines and it worked for me. 

Thanks again!

**Comment by davidtmiller** [comment]
Merged this one, thanks!
