### ISSUE TITLE
Links in social buttons

### ISSUE THREAD

**Issue by sarajohanna** [BlackrockDigital/startbootstrap-clean-blog#28]
When adding my own links to the social buttons, they only work if I right-click and choose "open in new tab". If pressed "normally" it re-directs to a blank page, URL still says page adress. When tested in Edge I get an error message saying "This content can not be displayed in a frame". As far as I'm concerned there are no frames on the page that would cause this. I've also tried creating links outside of bootstrap the same problem occur with these.

**Comment by davidtmiller** [comment]
Interesting bug here seeing as it's just a button with a link. I will see if I can replicate, but I am not sure if this is a problem with the theme or something else.

**Comment by sarajohanna** [comment]
I know, I don't really get it. That's why I had to write to you. Let me know if you find anything!

**Comment by davidtmiller** [comment]
I'm in the process of doing issue and bug cleanup this week and next so I'll check into this and see if I can replicate the bug.

**Comment by sarajohanna** [comment]
Thank you so much!

**Comment by davidtmiller** [comment]
I'm not able to replicate this bug so I'll be closing this for now. It might be something on your side specifically that's happening, perhaps some sort of AdBlock plugin or something of that nature?
