### ISSUE TITLE
Contact Form Broken

### ISSUE THREAD

**Issue by lnorton89** [BlackrockDigital/startbootstrap-clean-blog#29]
Nothing I do can get the contact form to work. Have change the line in the PHP file with an email account that isn't gmail/hotmail. Form submits but never receive mail.

**Comment by davidtmiller** [comment]
Interesting the form seems to be working elsewhere. This might be an issue with your web host. Also, the form wont work at all if you're hosting on GitHub pages.

**Comment by lnorton89** [comment]
I've tried on a local XAMPP server as well as a blank LAMP stack on Digital Ocean. I highly doubt my host(s) have anything to do with it.

**Comment by davidtmiller** [comment]
You've got a mail server running locally and everything?

**Comment by davidtmiller** [comment]
I am not seeing any issues with the form, and I'm not getting any other issues from other users. If you moved the files around make sure you fix the path in the `contact_me.js` file, but other than that I can't really think of anything else to try at this point...
