### ISSUE TITLE
Bootstrap navigation dropdown link text not visible

### ISSUE THREAD

**Issue by maccath** [BlackrockDigital/startbootstrap-clean-blog#42]
This is regarding the Bootstrap navigation component (http://getbootstrap.com/components/#navbar-default)

I have added the following HTML to the right area of the navigation bar:

```
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        Dropdown <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li><a href="#">Action</a></li>
        <li><a href="#">Another action</a></li>
        <li><a href="#">Something else here</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="#">Separated link</a></li>
    </ul>
</li>
```

However, on utilising this drop-down link, the links within the drop down menu are not visible unless you scroll down on the page (and thereby the links remain invisible if the page doesn't scroll).

I am happy to submit a fix for this.

**Comment by davidtmiller** [comment]
Merged.
