### ISSUE TITLE
Compile one CSS file only with Sass

### ISSUE THREAD

**Issue by vitoo** [BlackrockDigital/startbootstrap-clean-blog#63]
Hello,

I see you include 2 css file, 1 for bootstrap, and one for the theme
I try to compile 1 CSS file only with Sass, but i can't get it to work
How to achieve it ?
Here is what i've tried : 
```sass
@import 'node_modules/bootstrap/scss/bootstrap';

@import "variables.scss";
@import "mixins.scss";
@import "global.scss";
@import "navbar.scss";
@import "masthead.scss";
@import "post.scss";
@import "contact.scss";
@import "footer.scss";
@import "bootstrap-overrides.scss";
```
As you can see, the btn-primary color is not overrided (default bootstrap blue ?) : 
___
![Img](http://puu.sh/zNQ65/d36a2e25ad.png)
 ___
Thanks for your help

**Comment by davidtmiller** [comment]
Yes I keep them separated on purpose just for ease of use, but if you did want to combine them for a deployment scenario then you would want to load your overrides, then Bootstrap, then the rest of the styles.

`
@import 'node_modules/bootstrap/scss/bootstrap';

@import "bootstrap-overrides.scss";

@import "variables.scss";
@import "mixins.scss";
@import "global.scss";
@import "navbar.scss";
@import "masthead.scss";
@import "post.scss";
@import "contact.scss";
@import "footer.scss";
`

**Comment by vitoo** [comment]
Well, we have to import variable, then boostrap, then custom styles 
This worked : 

@import "variables.scss";

@import 'node_modules/bootstrap/scss/bootstrap';

```sass
@import "mixins.scss";
@import "global.scss";
@import "navbar.scss";
@import "masthead.scss";
@import "post.scss";
@import "contact.scss";
@import "footer.scss";
@import "bootstrap-overrides.scss";
```
