### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by HHZZUUJH** [BlackrockDigital/startbootstrap-clean-blog#65]
In the file index.php the background image is loaded from the web: $backgroundImage = 'https://source.unsplash.com/1600x900/?nature';

How can I include here own pictures on my webspace instead of the url?

Do I need my own license for https://source.unsplash.com/1600x900/?nature'?

**Comment by davidtmiller** [comment]
Just replace that link with a path to your own image and you're all set!
