### ISSUE TITLE
Change Jquery script into Vanilla JS

### ISSUE THREAD

**Issue by josuevalrob** [BlackrockDigital/startbootstrap-clean-blog#68]
Hi, I am trying to include React on this theme... 
Bootstrap is already replace and everything is fine, even the requirement with jquery. 
Now I want to remove jquery also from the clean-blog.js
The option A is doing it with React 100%. (Is what I am going to do)
And the option B, for no expert users is to stop using jquery, and use Vanilla js. 

Just that!  good luck! .

**Comment by davidtmiller** [comment]
I would check out this: https://react-bootstrap.github.io/
